### ISSUE TITLE
bvlc_alexnet.npy

### ISSUE THREAD

**Issue by assadRasheed** [LeeKyungMoon/Judging-a-Book-by-its-Cover#1]
I am trying to run your repository. I found the **bvlc_alexnet.npy** which need to be downloaded from the given link.i want to know that how your prepared this file. Can i prepared this file by myself.

**Comment by LeeKyungMoon** [comment]
**bvlc_alexnet.npy** is from [here](http://www.cs.toronto.edu/~guerzhoy/tf_alexnet/), not my repo.
I did prepare the raw image dataset from the [book-dataset](https://github.com/uchidalab/book-dataset) from Uchida-Lab using **"load_images.py"** in my repo as I mentioned.

Thanks, I'm closing this issue.

**Comment by assadRasheed** [comment]
i want to know that is this **bvlc_alexnet.npy** specifically used for this repo, Or i can used this for other datasets .
